server:
  port: 8080
  error:
    include-message: always
spring:
  application:
    name: geek-text
  datasource:
    username: 'group4'
    url: jdbc:mysql://localhost:3316/bookstore
    password: 'password'
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true